apiVersion: apps/v1
kind: Deployment
metadata:
  name: os-health-monitor
spec:
  template:
    spec:
      containers:
      - image: prom/prometheus:v2.24.0
        name: prom
        command:
        - sh
        - -c
        - |
            cat > /etc/prometheus/prometheus.yml <<EOF
            global:
              scrape_interval: 5s
            scrape_configs:
            - job_name: static
              static_configs:
              - targets:
                - localhost:8181
            EOF
            exec /bin/prometheus --config.file=/etc/prometheus/prometheus.yml
