apiVersion: apps/v1
kind: Deployment
metadata:
  name: os-health-monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: os-health-monitor
  template:
    metadata:
      labels:
        app: os-health-monitor
    spec:
      volumes:
      - name: dot-config-openstack
        secret:
          secretName: dot-config-openstack
      - name: telegraf-config
        configMap:
          name: telegraf-config
      containers:
      - image: telegraf:1.16.3-alpine
        name: telegraf
        readinessProbe:
          httpGet:
            path: /metrics
            port: 8181
        volumeMounts:
        - name: telegraf-config
          mountPath: /etc/telegraf
      - image: quay.io/sovereigncloudstack/openstack-health-monitor:latest
        name: os-health-monitor
        resources: {}
        volumeMounts:
        - name: dot-config-openstack
          mountPath: /etc/openstack
        env:
        - name: OS_CLOUD
          value: gx-scs-plusserver
        args: ['-n', '8', '-i', '10', '-S', '-o', '-D']
