apiVersion: apps/v1
kind: Deployment
metadata:
  name: os-health-monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: os-health-monitor
  template:
    metadata:
      labels:
        app: os-health-monitor
    spec:
      volumes:
      - name: dot-config-openstack
        secret:
          secretName: dot-config-openstack
      - name: telegraf-config
        configMap:
          name: telegraf-config
      containers:
      - image: telegraf:1.16.3-alpine
        name: telegraf
        readinessProbe:
          httpGet:
            path: /metrics
            port: 8181
        volumeMounts:
        - name: telegraf-config
          mountPath: /etc/telegraf
      - image: quay.io/sovereigncloudstack/openstack-health-monitor@sha256:9df59269670b81c5d663a58be5eed6e2ea481cb6758ee9cbba1480b6de297155
        name: os-health-monitor
        resources: {}
        volumeMounts:
        - name: dot-config-openstack
          mountPath: /root/.config/openstack
        env:
        - name: OS_CLOUD
          value: gx-scs-plusserver
        command:
        - sh
        - -c
        - |
            set -ex
            while [[ 0 = 0 ]]
            do
                openstack server list
                sleep 10
            done
